# Generated by Django 4.0.2 on 2022-03-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ttn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата рейса')),
                ('order_number', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Номер заявки клиента')),
                ('client', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Клиент (заказчик услуги 1-а)')),
                ('client_data', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='ИНН Клиента / юр.Адрес раздел 1-а')),
                ('cargoholder', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Грузоотправитель')),
                ('cargoholder_data', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='ИНН Грузоотправителя / юр.Адрес')),
                ('drop_on', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес погрузки')),
                ('cargorecipient', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Грузополучатель')),
                ('cargorecipient_data', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='ИНН Грузополучателя / юр.Адрес')),
                ('drop_off', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес выгрузки')),
                ('subclient', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Перевозчик')),
                ('subclient_data', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='ИНН Перевозчика / юр.адрес')),
                ('driver', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='ФИО Водителя')),
                ('truck', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Номер машины')),
                ('model', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Марка машины')),
                ('trailer', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Номер Прицепа')),
                ('cargo', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Груз')),
                ('pallet', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Количетсво мест')),
                ('weight', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Вес')),
                ('subclient_contract', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Реквизиты договора с перевозчиком ')),
                ('client_contract', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Реквизиты договора с клиентом ')),
            ],
            options={
                'verbose_name': 'ТН',
                'verbose_name_plural': 'ТН',
            },
        ),
    ]
