# Generated by Django 4.0.2 on 2022-02-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_ogrn'),
        ('addresses', '0003_alter_address_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.ForeignKey(limit_choices_to={'client_bool': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Клиент'),
        ),
    ]
