# Generated by Django 4.0.2 on 2022-03-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_alter_address_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=1024, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=1024, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='contact_person',
            field=models.CharField(max_length=1024, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Наименование точки погрузки'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=1024, verbose_name='Контактный телефон'),
        ),
    ]
