# Generated by Django 3.2.5 on 2022-03-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Контактный телефон'),
        ),
    ]
