# Generated by Django 4.0.2 on 2022-03-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_bank_name_alter_client_bik_and_more'),
        ('addresses', '0006_auto_20220305_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'client_bool': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Клиент'),
        ),
    ]
