# Generated by Django 4.0.2 on 2022-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Должность'),
        ),
    ]
