# Generated by Django 4.0.2 on 2022-03-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0003_profile_phone_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='file_name',
            field=models.CharField(max_length=1024, verbose_name='Наименование файла'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Должность'),
        ),
    ]
