# Generated by Django 3.2.7 on 2021-12-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=9, verbose_name='Номер тягача')),
                ('trailer_number', models.CharField(max_length=9, verbose_name='Номер прицепа')),
                ('type', models.CharField(max_length=4, verbose_name='Тент/Терм/Реф')),
                ('capacity', models.CharField(max_length=2, verbose_name='Грузовместимость')),
                ('vin_number', models.CharField(blank=True, max_length=17, verbose_name='VIN номер (необязательно)')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Марка/Модель/Цвет (необязательно)')),
                ('owner', models.CharField(blank=True, max_length=50, verbose_name='Собстенник (необязательно)')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
