# Generated by Django 3.2.7 on 2021-12-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_alter_truck_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.CharField(choices=[(1, '1,5т.'), (2, '3,5т.'), (3, '5т.'), (4, '10т.'), (5, '20т.')], max_length=6, verbose_name='Грузовместимость'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='type',
            field=models.CharField(choices=[(1, 'ТЕНТ'), (2, 'ТЕРМ'), (3, 'РЕФ'), (4, 'БОРТ'), (5, 'ТРАЛ')], max_length=5, verbose_name='Тент/Терм/Реф'),
        ),
    ]
