# Generated by Django 3.2.7 on 2021-12-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20211220_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.CharField(choices=[('1,5т.', '1,5т.'), ('3,5т.', '3,5т.'), ('5т.', '5т.'), ('10т.', '10т.'), ('20т.', '20т.')], max_length=6, verbose_name='Грузовместимость'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='type',
            field=models.CharField(choices=[('ТЕНТ', 'ТЕНТ'), ('ТЕРМ', 'ТЕРМ'), ('РЕФ', 'РЕФ'), ('БОРТ', 'БОРТ'), ('ТРАЛ', 'ТРАЛ')], max_length=5, verbose_name='Тент/Терм/Реф'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin_number',
            field=models.CharField(blank=True, max_length=18, verbose_name='VIN номер (необязательно)'),
        ),
    ]
