# Generated by Django 4.0.2 on 2022-02-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_ogrn'),
        ('trucks', '0004_auto_20211220_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'subclient_bool': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Выберите перевозчика'),
        ),
    ]
