# Generated by Django 4.0.2 on 2022-03-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_alter_truck_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='brand',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Марка/Модель/Цвет (необязательно)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.CharField(choices=[('1,5т.', '1,5т.'), ('3,5т.', '3,5т.'), ('5т.', '5т.'), ('10т.', '10т.'), ('20т.', '20т.')], max_length=1024, verbose_name='Грузовместимость'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='trailer_number',
            field=models.CharField(max_length=1024, verbose_name='Номер прицепа'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_number',
            field=models.CharField(max_length=1024, verbose_name='Номер тягача'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='type',
            field=models.CharField(choices=[('ТЕНТ', 'ТЕНТ'), ('ТЕРМ', 'ТЕРМ'), ('РЕФ', 'РЕФ'), ('БОРТ', 'БОРТ'), ('ТРАЛ', 'ТРАЛ')], max_length=1024, verbose_name='Тент/Терм/Реф'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin_number',
            field=models.CharField(blank=True, max_length=1024, verbose_name='VIN номер (необязательно)'),
        ),
    ]
