# Generated by Django 3.2.5 on 2022-03-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0018_order_sale_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Ожидаем документы', 'Ожидаем документы'), ('В работе ДО', 'В работе ДО'), ('На согласовании ФК', 'На согласовании ФК'), ('Согласован', 'Согласован'), ('Отклонен', 'Отклонен'), ('Оплачен перевозчику', 'Оплачен перевозчику'), ('Передан клиенту', 'Передан клиенту'), ('Оплачен клиентом', 'Оплачен клиентом')], default='Ожидаем документы', max_length=1024, null=True, verbose_name='Статус документооборота')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Документооборот',
                'verbose_name_plural': 'Документооборот',
            },
        ),
    ]
