# Generated by Django 3.2.5 on 2022-03-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docflow',
            name='date_agreed',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата Согласован'),
        ),
        migrations.AddField(
            model_name='docflow',
            name='date_fk',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата На согласовании ФК'),
        ),
        migrations.AddField(
            model_name='docflow',
            name='date_in_work',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата В работе ДО'),
        ),
        migrations.AddField(
            model_name='docflow',
            name='date_paid',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата Оплачен перевозчику'),
        ),
        migrations.AddField(
            model_name='docflow',
            name='date_paid_client',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата Оплачен клиентом'),
        ),
        migrations.AddField(
            model_name='docflow',
            name='date_rejected',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата Отклонен'),
        ),
        migrations.AddField(
            model_name='docflow',
            name='date_send',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата Передан клиенту'),
        ),
    ]
