# Generated by Django 3.2.5 on 2022-03-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0002_auto_20220310_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='docflow',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Номер счета'),
        ),
        migrations.AddField(
            model_name='docflow',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='docflow',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата получения документов'),
        ),
        migrations.AddField(
            model_name='docflow',
            name='manager_do',
            field=models.CharField(blank=True, choices=[('Гринева', 'Гринева'), ('Спирин', 'Спирин'), ('Титова', 'Титова'), ('Прибойко', 'Прибойко')], max_length=1024, null=True, verbose_name='Ответсвенный специалист'),
        ),
    ]
