# Generated by Django 4.0.2 on 2022-03-17 08:16

import django.core.files.storage
from django.db import migrations, models
import docflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0003_auto_20220310_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='docflow',
            name='subclient_document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=docflow.models.DocFlow.get_upload_to, verbose_name='Заявка с перевозчиком'),
        ),
        migrations.AddField(
            model_name='docflow',
            name='ttn_document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=docflow.models.DocFlow.get_upload_to, verbose_name='ТТН'),
        ),
    ]
