# Generated by Django 3.2.7 on 2021-12-20 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО Водителя')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('passport_numbers', models.CharField(max_length=10, verbose_name='Серия/номер паспорта')),
                ('passport', models.CharField(max_length=200, verbose_name='Паспортные данные')),
                ('passport_date', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('registration', models.CharField(max_length=200, verbose_name='Прописка')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('driver_license', models.CharField(max_length=10, verbose_name='Номер водительского удостоверения')),
                ('inn', models.CharField(max_length=12, verbose_name='Номер ИНН')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
    ]
