# Generated by Django 4.0.2 on 2022-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_date',
            field=models.DateField(verbose_name='Дата выдачи паспорта'),
        ),
    ]
