# Generated by Django 4.0.2 on 2022-02-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_birthday_alter_driver_passport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
    ]
