# Generated by Django 4.0.2 on 2022-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
