# Generated by Django 4.0.2 on 2022-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_driver_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
    ]
