# Generated by Django 3.2.7 on 2021-12-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Наименование фирмы')),
                ('juridical_address', models.CharField(max_length=200, verbose_name='Юридический адрес')),
                ('post_address', models.CharField(max_length=200, verbose_name='Почтовый адрес')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=13, verbose_name='КПП')),
                ('bik', models.CharField(max_length=9, verbose_name='БИК')),
                ('payment_score', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('correspondent_score', models.CharField(max_length=20, verbose_name='Корреспондентский счет')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Наименование банка')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Контактный телефон')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Контактное лицо')),
                ('client_bool', models.BooleanField(default=False, verbose_name='Является клиентом')),
                ('subclient_bool', models.BooleanField(default=False, verbose_name='Является перевозчиком')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
