# Generated by Django 3.2.7 on 2021-12-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ogrn',
            field=models.CharField(max_length=13, verbose_name='ОГРН'),
        ),
    ]
