# Generated by Django 4.0.2 on 2022-02-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_ogrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract_data',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Номер и дата договора'),
        ),
    ]
