# Generated by Django 4.0.2 on 2022-03-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_contract_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bank_name',
            field=models.CharField(max_length=1024, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bik',
            field=models.CharField(max_length=1024, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=1024, verbose_name='Наименование фирмы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(max_length=1024, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_data',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Номер и дата договора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='correspondent_score',
            field=models.CharField(max_length=1024, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(max_length=1024, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='juridical_address',
            field=models.CharField(max_length=1024, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.CharField(max_length=1024, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ogrn',
            field=models.CharField(max_length=1024, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_score',
            field=models.CharField(max_length=1024, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=1024, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='post_address',
            field=models.CharField(max_length=1024, verbose_name='Почтовый адрес'),
        ),
    ]
