# Generated by Django 4.0.2 on 2022-03-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_bank_name_alter_client_bik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bik',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='client',
            name='correspondent_score',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='juridical_address',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ogrn',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_score',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='post_address',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Почтовый адрес'),
        ),
    ]
