# Generated by Django 3.2.7 on 2021-12-23 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0003_alter_address_client'),
        ('trucks', '0004_auto_20211220_1754'),
        ('drivers', '0001_initial'),
        ('clients', '0002_alter_client_ogrn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата рейса')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер рейса')),
                ('date_on', models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата погрузки')),
                ('date_off', models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата выгрузки')),
                ('cargo', models.CharField(max_length=100, verbose_name='Груз')),
                ('pallet', models.IntegerField(default=0, verbose_name='Количество паллет')),
                ('required_type', models.CharField(choices=[('ТЕНТ', 'ТЕНТ'), ('ТЕРМ', 'ТЕРМ'), ('РЕФ', 'РЕФ'), ('БОРТ', 'БОРТ'), ('ТРАЛ', 'ТРАЛ')], max_length=5, verbose_name='Тент/Терм/Реф')),
                ('client_cost', models.IntegerField(default=0, verbose_name='Ставка клиента')),
                ('subclient_cost', models.IntegerField(default=0, verbose_name='Ставка перевозчика')),
                ('logist', models.CharField(choices=[('Петров', 'Петров'), ('Козарезов', 'Козарезов')], max_length=20, verbose_name='Логист')),
                ('client', models.ForeignKey(limit_choices_to={'client_bool': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_client', to='clients.client', verbose_name='Клиент')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drivers.driver', verbose_name='Водитель')),
                ('drop_off', models.ForeignKey(limit_choices_to={'drop_off': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_drop_off', to='addresses.address', verbose_name='Точка выгрузки')),
                ('drop_on', models.ForeignKey(limit_choices_to={'drop_on': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_drop_on', to='addresses.address', verbose_name='Точка погрузки')),
                ('subclient', models.ForeignKey(limit_choices_to={'subclient_bool': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_subclient', to='clients.client', verbose_name='Перевозчик')),
                ('truck', models.ForeignKey(limit_choices_to={'type': models.CharField(choices=[('ТЕНТ', 'ТЕНТ'), ('ТЕРМ', 'ТЕРМ'), ('РЕФ', 'РЕФ'), ('БОРТ', 'БОРТ'), ('ТРАЛ', 'ТРАЛ')], max_length=5, verbose_name='Тент/Терм/Реф')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trucks.truck', verbose_name='Номер машины')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
    ]
