# Generated by Django 3.2.5 on 2022-01-27 13:34

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subclient_document',
            field=models.FileField(null=True, upload_to=orders.models.Order.get_upload_to, verbose_name='Заявка с перевозчиком'),
        ),
    ]
