# Generated by Django 4.0.2 on 2022-02-07 13:13

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_subclient_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ttn_document',
            field=models.FileField(null=True, upload_to=orders.models.Order.get_upload_to, verbose_name='ТТН'),
        ),
    ]
