# Generated by Django 4.0.2 on 2022-02-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_ttn_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Текущая', 'Текущая'), ('Новая', 'Новая'), ('Закрыта', 'Закрыта'), ('Выполнена', 'Выполнена'), ('Бронь', 'Бронь'), ('Срыв', 'Срыв'), ('Обнулена', 'Обнулена')], default='Новая', max_length=10, verbose_name='Статус заявки'),
        ),
    ]
