# Generated by Django 4.0.2 on 2022-02-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Актуальная', 'Актуальная'), ('Выполнена', 'Выполнена'), ('Бронь', 'Бронь'), ('Срыв', 'Срыв'), ('Обнулена', 'Обнулена')], default='Актуальная', max_length=10, verbose_name='Статус заявки'),
        ),
    ]
