# Generated by Django 4.0.2 on 2022-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo',
            field=models.CharField(max_length=100, null=True, verbose_name='Груз'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Дата рейса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_off',
            field=models.DateTimeField(verbose_name='Дата выгрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_on',
            field=models.DateTimeField(verbose_name='Дата погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logist',
            field=models.CharField(choices=[('Петров', 'Петров'), ('Козарезов', 'Козарезов')], max_length=20, null=True, verbose_name='Логист'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер рейса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subclient_cost',
            field=models.IntegerField(null=True, verbose_name='Ставка перевозчика'),
        ),
    ]
