# Generated by Django 4.0.2 on 2022-02-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_auto_20211220_1754'),
        ('drivers', '0002_alter_driver_birthday_alter_driver_passport_date'),
        ('clients', '0002_alter_client_ogrn'),
        ('addresses', '0004_alter_address_client'),
        ('orders', '0010_alter_order_cargo_alter_order_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(limit_choices_to={'client_bool': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_client', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drop_off',
            field=models.ForeignKey(limit_choices_to={'drop_off': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_drop_off', to='addresses.address', verbose_name='Точка выгрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drop_on',
            field=models.ForeignKey(limit_choices_to={'drop_on': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_drop_on', to='addresses.address', verbose_name='Точка погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subclient',
            field=models.ForeignKey(blank=True, default=' ', limit_choices_to={'subclient_bool': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_subclient', to='clients.client', verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='truck',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trucks.truck', verbose_name='Номер машины'),
        ),
    ]
