# Generated by Django 4.0.2 on 2022-02-12 14:33

import django.core.files.storage
from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_client_alter_order_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subclient_document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=orders.models.Order.get_upload_to, verbose_name='Заявка с перевозчиком'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ttn_document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=orders.models.Order.get_upload_to, verbose_name='ТТН'),
        ),
    ]
