# Generated by Django 4.0.2 on 2022-02-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_alter_truck_owner'),
        ('drivers', '0002_alter_driver_birthday_alter_driver_passport_date'),
        ('clients', '0002_alter_client_ogrn'),
        ('orders', '0012_alter_order_subclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Груз'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logist',
            field=models.CharField(blank=True, choices=[('Петров', 'Петров'), ('Козарезов', 'Козарезов')], default='', max_length=20, null=True, verbose_name='Логист'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Номер рейса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subclient',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'subclient_bool': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_subclient', to='clients.client', verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='truck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trucks.truck', verbose_name='Номер машины'),
        ),
    ]
