# Generated by Django 3.2.5 on 2022-03-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220301_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_dispatcher',
            field=models.CharField(blank=True, choices=[('В пути на погрузку', 'В пути на погрузку'), ('На погрузке', 'На погрузке'), ('В пути на выгрузку', 'В пути на выгрузку'), ('На выгрузке', 'На выгрузке'), ('Нет связи', 'Нет связи'), ('Рейс окончен, документы получены', 'Рейс окончен, документы получены'), ('Опаздывает', 'Опаздывает'), ('Поломка', 'Поломка')], max_length=50, null=True, verbose_name='Статус диспетчера'),
        ),
    ]
