# Generated by Django 4.0.2 on 2022-03-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_status_dispatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Груз'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logist',
            field=models.CharField(blank=True, choices=[('Домашенко А.А.', 'Домашенко А.А.'), ('Дымшиц Е.М.', 'Дымшиц Е.М.'), ('Саморай А.П.', 'Саморай А.П.'), ('Вотрин Р.В.', 'Вотрин Р.В.'), ('Ширяева Д.В.', 'Ширяева Д.В.'), ('Панасенко А.И.', 'Панасенко А.И.'), ('Максимович О.В.', 'Максимович О.В.')], default='', max_length=1024, null=True, verbose_name='Логист'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Номер рейса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Актуальная', 'Актуальная'), ('Бронь', 'Бронь'), ('Срыв', 'Срыв'), ('Обнулена', 'Обнулена'), ('ТС назначен', 'ТС назначен'), ('Выполнена', 'Выполнена')], default='Актуальная', max_length=1024, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_dispatcher',
            field=models.CharField(blank=True, choices=[('В пути на погрузку', 'В пути на погрузку'), ('На погрузке', 'На погрузке'), ('В пути на выгрузку', 'В пути на выгрузку'), ('На выгрузке', 'На выгрузке'), ('Нет связи', 'Нет связи'), ('Рейс окончен, документы получены', 'Рейс окончен, документы получены'), ('Опаздывает', 'Опаздывает'), ('Поломка', 'Поломка')], max_length=1024, null=True, verbose_name='Статус диспетчера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_do',
            field=models.CharField(blank=True, choices=[('Ожидаем документы', 'Ожидаем документы'), ('В работе ДО', 'В работе ДО'), ('На согласовании ФК', 'На согласовании ФК'), ('Согласован', 'Согласован'), ('Отклонен', 'Отклонен'), ('Оплачен', 'Оплачен')], max_length=1024, null=True, verbose_name='Статус документооборота'),
        ),
    ]
