# Generated by Django 4.0.2 on 2022-03-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_cargo_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Актуальная', 'Актуальная'), ('Бронь', 'Бронь'), ('Срыв', 'Срыв'), ('Закрыта КА', 'Закрыта КА'), ('Обнулена', 'Обнулена'), ('ТС назначен', 'ТС назначен'), ('Выполнена', 'Выполнена')], default='Актуальная', max_length=1024, verbose_name='Статус заявки'),
        ),
    ]
