# Generated by Django 3.2.5 on 2022-03-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_sale_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_do',
        ),
    ]
