# Generated by Django 4.0.2 on 2022-03-20 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_auto_20220305_1745'),
        ('orders', '0019_remove_order_status_do'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата погрузки/выгрузки')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address', verbose_name='Доп. Точка погрузки/выгрузки')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Рейс')),
            ],
        ),
    ]
