# Generated by Django 4.0.2 on 2022-03-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_auto_20220305_1745'),
        ('orders', '0022_orderadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_off_plus',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доп.Дата выгрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_on_plus',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доп.Дата погрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='drop_off_plus',
            field=models.ForeignKey(blank=True, limit_choices_to={'drop_off': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_drop_off_plus', to='addresses.address', verbose_name='Доп.Точка выгрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='drop_on_plus',
            field=models.ForeignKey(blank=True, limit_choices_to={'drop_on': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_drop_on_plus', to='addresses.address', verbose_name='Доп.Точка погрузки'),
        ),
        migrations.DeleteModel(
            name='OrderAdress',
        ),
    ]
