# Generated by Django 4.0.2 on 2022-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_date_off_plus_order_date_on_plus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='required_info',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Доп.требования к ТС'),
        ),
    ]
