# Generated by Django 4.0.2 on 2022-04-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_order_sale_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_cost',
            field=models.FloatField(default=0, verbose_name='Ставка клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subclient_cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ставка перевозчика'),
        ),
    ]
