# Generated by Django 4.0.2 on 2022-05-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_order_client_cost_alter_order_subclient_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale_manager',
            field=models.CharField(blank=True, choices=[('Крушельницкая Р.А.', 'Крушельницкая Р.А.'), ('Новосельцева Г.А.', 'Новосельцева Г.А.'), ('Иовлева С.В.', 'Иовлева С.В.'), ('Марушко А.О', 'Марушко А.О'), ('Коновалов Н.А', 'Коновалов Н.А'), ('Сафонова А. В.', 'Сафонова А. В.'), ('Соловьева Н.А.', 'Соловьева Н.А.'), ('Карнаухова Т.В.', 'Карнаухова Т.В.'), ('Лещенко Е.В', 'Лещенко Е.В'), ('Павлов Г.Н', 'Павлов Г.Н'), ('Колесник Д.В.', 'Колесник Д.В.'), ('Кругликов С.И.', 'Кругликов С.И.'), ('Кремнев А.А.', 'Кремнев А.А.'), ('Потапенко М.С.', 'Потапенко М.С.'), ('Мешкова А.М.', 'Мешкова А.М.')], default='', max_length=1024, null=True, verbose_name='Клиентский менеджер'),
        ),
    ]
